# Generated by Django 3.2.2 on 2023-10-29 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desginerUpload',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('design_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.CharField(max_length=100)),
                ('_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
