# Generated by Django 4.1.12 on 2023-11-02 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desginerUpload',
            fields=[
                ('design_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.JSONField(blank=True, default=dict, null=True)),
                ('_image', models.BinaryField(null=True)),
                ('uploaderEmail', models.CharField(blank=True, max_length=255)),
                ('isPremimum', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDesigns',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('old_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.JSONField(blank=True, default=dict, null=True)),
                ('_image', models.BinaryField(null=True)),
                ('uploaderEmail', models.CharField(blank=True, max_length=255)),
                ('isPremimum', models.BooleanField(default=False)),
                ('isSold', models.BooleanField(default=False)),
            ],
        ),
    ]
