# Generated by Django 4.1.12 on 2023-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopDesigns',
        ),
        migrations.AddField(
            model_name='desginerupload',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desginerupload',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='desginerupload',
            name='_image',
            field=models.BinaryField(),
        ),
    ]
