# Generated by Django 4.1.12 on 2023-11-01 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDesigns',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('old_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
                ('_image', models.ImageField(upload_to='')),
                ('isPremimum', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='desginerupload',
            name='isPremimum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desginerupload',
            name='uploaderEmail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
